In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [9]:
hello = tf.constant('Hello Tensor!')
hello.numpy()

b'Hello Tensor!'

In [10]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [12]:
type(hello.numpy())

bytes

In [13]:
hello.numpy().decode('utf-8')

'Hello Tensor!'

In [16]:
type(hello.numpy().decode('utf-8'))

str

In [17]:
kor = tf.constant('한글')
kor

<tf.Tensor: shape=(), dtype=string, numpy=b'\xed\x95\x9c\xea\xb8\x80'>

In [20]:
kor.numpy().decode('utf-8')

'한글'

In [28]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

d = tf.add (a, b)
e = tf.multiply(d, c)

In [26]:
d.numpy()

5

In [29]:
e.numpy()

25

In [34]:
matrixA = tf.constant([[1, 2],
                     [3, 4]])
matrixB = tf.constant([[2,0], [0,2]])
matrixA

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [38]:
matrixC = tf.multiply(matrixA, matrixB)
matrixC

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 0],
       [0, 8]])>

In [39]:
matrixC.numpy()

array([[2, 0],
       [0, 8]])