In [1]:
import tensorflow as tf

In [10]:
tensor = tf.constant([3, 4, 5])
tensor2 = tf.constant([6, 7, 8])

tensor3 = tf.constant([[1, 2], 
                 [3, 4]])

tf.add() 더하기
tf.subtract() 빼기
tf.divide() 나누기
tf.multiply() 곱
tf.matmul() 행렬곱
tf.zeros() 0으로 이루어진 행렬 생성 괄호 안에는 갯수 혹은 shape

In [12]:
tensor4 = tf.zeros(10)
tensor5 = tf.zeros([2, 2])

print(tensor4)
print(tensor5)
print(tensor4.shape)
print(tensor5.shape)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
(10,)
(2, 2)


In [15]:
print(tensor.dtype)
print(tensor.shape)
print(tensor)

<dtype: 'int32'>
(3,)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [17]:
w = tf.Variable(1.0) # 변경할 때 쓰는 듯
print(w)
print(w.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
1.0


In [18]:
w.assign(2)
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>